#!/usr/bin/env python

import httplib
from pylms.server import Server
from pylms.player import Player

sc = Server(hostname="192.168.1.111", port=9090)
sc.connect()

print "Logged in: %s" % sc.logged_in
print "Version: %s" % sc.get_version()

sq = sc.get_player("00:04:20:07:98:43")

sq.get_mode()
print "Name: %s | Mode: %s | Time: %s | Connected: %s | WiFi: %s" % (sq.get_name(), sq.get_mode(), sq.get_time_elapsed(), sq.is_connected, sq.get_wifi_signal_strength())

if sq.get_mode() == 'play':
  artist = sq.get_track_artist()
  album = sq.get_track_album()
  title = sq.get_track_title()

  print "%s - %s - %s" % (artist, album, title)
elif sq.get_mode() == 'stop':
  print "Nothing's playing"
