#! /usr/bin/env ruby

require 'net/http'
require 'uri'

# get secret key for posting to server
f = File.open('/Users/mgeraci/Web/Now-Playing/secretkey.txt', 'r')

while line = f.gets
  secret = line
end
f.close

# get info from itunes if playing
if `osascript -e 'tell application "iTunes" to get player state'`.gsub(/\s/, '') == 'playing'
  artist = `osascript -e 'tell application "iTunes" to get artist of current track'`
  year = `osascript -e 'tell application "iTunes" to get year of current track'`
  album = `osascript -e 'tell application "iTunes" to get album of current track'`
  title = `osascript -e 'tell application "iTunes" to get name of current track'`

  puts artist
  puts year
  puts album
  puts title
  puts secret

  #params = "&artist=#{artist}&album=#{album}&title=#{title}&secret=#{secret}"
  #response = http.post('http://127.0.0.1:3000/add_song', params)

  url = URI('http://127.0.0.1:3000/add_song')
  #url = URI('http://now-playing.meteor.com/add_song')
  args = {
    'artist' => artist,
    'album' => album,
    'title' => title,
    'secret' => secret
  }

  res = Net::HTTP.post_form url, args
  puts res.body
else
  puts 'nothing is on!'
end
