#!/usr/bin/env python

import httplib, urllib
from pylms.server import Server
from pylms.player import Player

sc = Server(hostname="192.168.1.111", port=9090)
sc.connect()

print "Logged in: %s" % sc.logged_in
print "Version: %s" % sc.get_version()

sq = sc.get_player("00:04:20:07:98:43")

if sq.get_mode() == 'play':
  artist = sq.get_track_artist()
  album = sq.get_track_album()
  title = sq.get_track_title()

  print "%s - %s - %s" % (artist, album, title)
  print ""

  params = urllib.urlencode({'artist': artist, 'album': album, 'title': title})
  conn = httplib.HTTPConnection("127.0.0.1:3000")
  url = "/add_song?%s" % (params)

  print "posting..."
  conn.request('GET', url)
  response = conn.getresponse()

  print response.status, response.reason

  conn.close()
elif sq.get_mode() == 'stop':
  print "Nothing's playing"
